### ISSUE TITLE
Wav Loop Points & Recommendation

### ISSUE THREAD

**Issue by Carldacious** [bkacjios/m-overlay#78]
I commented on the original post, but I am unsure if it has been seen since it has been closed:
https://github.com/bkacjios/m-overlay/issues/48#issuecomment-802759674

I have been experimenting with this, using the WAV file that CinnaminionTGM provided (ClockTowerStage), and I am not having any luck getting the loop to work correctly on the latest version of m-overlay (1.7). I also tried adding markers to some files of my own and no luck either. I confirmed in Wavosaur that the markers were present. m-overlay just restarts playback from the beginning when the file ends.

I wanted to ask if this feature could be implemented differently, so that it would not be limited to WAV files. Could you use "LOOP_START" and "LOOP_END" in a file's metadata to inform/activate the loop point? The value in each field would be the number of the sample in the file where it (the loop start or end) occurs.

You could add this information to virtually any audio file using mp3tag: https://www.mp3tag.de/en/download.html
Note: You need to manually add the fields "LOOP_START" and "LOOP_END", as they are not in mp3tag by default.

If you wanted to test your loop using this method, you would need foobar2000 and the vgmstream plugin:
Foobar: https://www.foobar2000.org/download
vgmstream: https://www.foobar2000.org/components/view/foo_input_vgmstream

In preferences in Foobar, make sure under the vgmstream component that 'Loop Forever' is checked. Then, temporarily change the file's extension to have an "l" in front of it. For example, 'flac' becomes 'lflac' or 'ogg' becomes 'logg'. Here is a file for testing:

[FD-logg.zip](https://github.com/bkacjios/m-overlay/files/6170683/FD-logg.zip)

**Comment by bkacjios** [comment]
The ClockTowerStage file seems to work and loop fine for me. Just so you know, the loop points will not work in playlist mode. Maybe that's your problem?

Even still, I added some debugging and it's working as intended.

![debug](https://i.imgur.com/d6LDB0I.png)

The loop point is at the end of the song, so when the song ends, it seeks to the sample at sample_start. You can see that the song loops back to 0, but then my custom code sets it to the loop point sample `416185`

But to answer your suggestion, it's not that easy to just add information to any audio file. Each audio file format has different header structures, and I'm not about to go and make an implementation for all of them. It's not as simple as just using the files metadata. I need to be able to decode it. If you would like to implement it for the other formats, I would welcome a pull request. You could use my wav parser as a starting point. https://github.com/bkacjios/m-overlay/blob/master/source/modules/wav.lua

[m-overlay-x64 (master-230).zip](https://github.com/bkacjios/m-overlay/files/6217997/m-overlay-x64.master-230.zip)

I made this little debug build for you to try if you'd like. Just be sure to enable the debug console in the settings menu. You should see stuff like this..

```
GOT WAV DATA    Melee/Menu Music/ClockTowerStage.wav
[SONG FINISHED] position = 0
seeking 415744
```

**Comment by Carldacious** [comment]
Thank you very much for this reply and the debug build!

I have m-overlay in 'Loop All' mode. Everything I see that you are saying makes sense with your code. For some reason it is not jumping to the appropriate sample start. It just restarts at the beginning as it did before. I am not getting the [SONG FINISHED] or the seeking section you shared. Any reason that might happen? I am using the debug build you supplied. Thank you very much for doing that.

![image](https://user-images.githubusercontent.com/68999000/112822612-2a86da00-9056-11eb-87ac-17eecda2d5f3.png)

I should have considered that the header/tags would be different per audio file, I understand how much work that would be to support each file type. I would love to be able to help implement it for other formats, but I am not sure where to start (other than with your WAV starting point). Not to ask too much, but if you have any resources on steps to adapt your code appropriately I would be interested. I am willing to put in the work but I have not done much coding myself. The format I care most about is FLAC because it saves more space without loss in quality, but having loop points in any regard is cool. I just wish I could get them to work.

**Comment by bkacjios** [comment]
That's really strange.. I have no idea why it wouldn't work. I'll make another build with more debug info to try and figure out what's going on a bit later.

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-230).zip](https://github.com/bkacjios/m-overlay/files/6223446/m-overlay-x64.master-230.zip)

Okay, here's another build. It should print a lot more info for me to look at now. If it starts spamming your console with a lot of data when the song is playing then it should be working.

**Comment by Carldacious** [comment]
Thanks for this! Still not looping unfortunately:

![image](https://user-images.githubusercontent.com/68999000/112879916-cc7ae680-9097-11eb-8eeb-48af8ee02888.png)

Here's the location where it starts from the beginning of the file:

![image](https://user-images.githubusercontent.com/68999000/112880059-f8966780-9097-11eb-9bc9-738ff089a34a.png)

**Comment by bkacjios** [comment]
Okay well that explains it. It's not parsing the `smpl` data for you inside the wav.

For example, this is what mine looks like when loading.
![data](https://i.imgur.com/GSkNlkj.png)

`found 'smpl' info       1` means it found 1 loop.

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-230).zip](https://github.com/bkacjios/m-overlay/files/6224557/m-overlay-x64.master-230.zip)

Okay, try this out. I guess whatever program you used to edit or view the loop points put the loop data after the PCM data. It should now parse the entire file now, which should hopefully fix your issue.

**Comment by Carldacious** [comment]
Ah-hah! This seems to have fixed the issue with looping!  Thank you!

What's strange is this issue occurred for me even if I did not view the _ClockTowerStage.wav_ in any program and extracted it straight from the ZIP. It may not matter at this point as this issue seems resolved, but I am using Wavosaur to view/add loop data.

Unfortunately there's one last issue I noticed. When returning to the designated loop point, there's a delay, which means it's not a fluid loop. I checked ClockTowerStage and a loop I made myself and in removing the silence (that's not originally there), the loop transitions fluidly.

I recorded the output of m-overlay into Audacity to show what I mean:

https://user-images.githubusercontent.com/68999000/112934977-d67d0380-90f0-11eb-865e-026747ef77c1.mp4

**Comment by Carldacious** [comment]
I understand. I had to ask just in case there was a fix. Thanks for all of your help on this! This is super cool!

**Comment by bkacjios** [comment]
I'll get 1.7.1 released later today to resolve this and remove all the debug spam from the console

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.7.1
